# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_ANDES_CACHE)		+= andes_llcache.o
obj-$(CONFIG_SIFIVE_CCACHE)		+= sifive_ccache.o
obj-$(CONFIG_STARFIVE_STARLINK_CACHE)	+= starfive_starlink_cache.o

obj-$(CONFIG_HISI_SOC_HHA)		+= hisi_soc_hha.o
