# SPDX-License-Identifier: GPL-2.0-only
#
# Build linkable blobs
#

blobs	:= $(addprefix $(obj)/, $(blobs))

blob-stem = $(subst -,_,$(subst .blob,,$(basename $(patsubst $(obj)/%,%,$@))))
blob-symbol = $(or $($(target-stem)-symbol),$(blob-stem))

blob-flags = -DBLOB_SYMBOL="$(blob-symbol)" -DBLOB_INPUT=$<

quiet_cmd_blob = BLOB    $@
      cmd_blob = $(CC) $(c_flags) $(blob-flags) -c -o $@ $(srctree)/scripts/blob-wrap.c

$(blobs): $(obj)/%.blob.o: $(obj)/% $(srctree)/scripts/blob-wrap.c FORCE
	$(call if_changed_dep,blob)

targets += $(blobs)
