# SPDX-License-Identifier: GPL-2.0-only
#
# Makefile for drivers that support virtualization
#

obj-$(CONFIG_FSL_HV_MANAGER)	+= fsl_hypervisor.o
obj-$(CONFIG_VMGENID)		+= vmgenid.o
obj-y				+= vboxguest/

obj-$(CONFIG_NITRO_ENCLAVES)	+= nitro_enclaves/
obj-$(CONFIG_ACRN_HSM)		+= acrn/
obj-y				+= coco/
obj-$(CONFIG_BAO_SHMEM)		+= bao/
obj-$(CONFIG_BAO_IO_DISPATCHER)	+= bao/
